### ISSUE TITLE
`helper` in controller decorator is ignored/overwritten in production

### ISSUE THREAD

**Issue by jreinert** [parndt/decorators#14]
I use the decorators gem among other things for monkey patching `DeviseController`. In the `class_eval` block I use `helper` to include my `ApplicationHelper` and other helpers. This works fine in development, but in production I get a `NoMethodError` in a view that tries to call a helper method in my `ApplicationHelper`.

I double checked that my decorator get's loaded. I also added a `before_filter` in the decorator and It's being called as well. Only the helpers aren't included.

Here's my code:

``` ruby
DeviseController.class_eval do
  layout 'admin'
  append_view_path 'app/views/admin'
  has_mobile_fu
  before_filter :init_js_framework_settings
  $stderr.puts('GETS LOADED!')

  protected

    def init_js_framework_settings
      @js_framework_settings = {
        namespace: self.class.name.split('::')[0..-2],
        controller: controller_name.camelize,
        action: action_name
      }
    end
end
```

**Comment by jreinert** [comment]
umm.. any reason you closed this?

**Comment by parndt** [comment]
It has been open for over a year, that's the only reason. Are you still having this problem? If so, please feel free to reopen it.

I also can't see your call to helper in the example code you posted? 😄

**Comment by parndt** [comment]
You may want to try this version of your decorator:

```ruby
module CustomDeviseControllerModule
  layout 'admin'
  append_view_path 'app/views/admin'
  has_mobile_fu
  before_action :init_js_framework_settings
  $stderr.puts('GETS LOADED!')

  prepended do
    helper ApplicationHelper # your helper call here
  end

  protected

    def init_js_framework_settings
      @js_framework_settings = {
        namespace: self.class.name.split('::')[0..-2],
        controller: controller_name.camelize,
        action: action_name
      }
    end
end

# you can avoid using send to invoke prepend if you're using a recent enough Ruby version
DeviseController.send :prepend, CustomDeviseControllerModule
```
